global:
  scrape_interval: 15s

  external_labels:
    monitor: 'codelab-monitor'

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    target_groups:
      - targets: ['localhost:9090']

  - job_name: 'secure-module'
    scrape_interval: 5s
    target_groups:
      - targets: ['ota-secure-module:28080']

  - job_name: 'ota-gateway-blocking'
    scrape_interval: 5s
    target_groups:
      - targets: ['ota-gateway-blocking:28080']

  - job_name: 'ota-gateway-non-blocking'
    scrape_interval: 5s
    target_groups:
      - targets: ['ota-gateway-non-blocking:28080']
