prometheus:
  image: prom/prometheus

  ports:
    - 9090:9090

  expose:
    - 9090

  volumes:
    - ./conf/prometheus.yml:/etc/prometheus/prometheus.yml:ro

graphana:
  image: grafana/grafana
  links:
    - prometheus

  ports:
    - 3000:3000

  environment:
    GF_SERVER_ROOT_URL: http://192.168.99.100:3000
    GF_SECURITY_ADMIN_PASSWORD: secret
